# Generated by Django 4.0.1 on 2022-02-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_pro_pic',
            field=models.FileField(default='/default/default_pro.png', upload_to='media/user-pro-pic/'),
        ),
    ]
