# Generated by Django 4.0.1 on 2022-02-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pro_pic',
            field=models.FileField(blank=True, upload_to='media/user-pro-pic/'),
        ),
    ]
